Parsing "+(+!![]+(!![]+[])[!![]+!![]+!![]]+(+!![]+[+[]+[+[]+[+[]]]]))"

Completed in
  18 minutes
  2 seconds
  5 ms

{UnaryExpression
 +
 {UnaryExpression
  {UpdateExpression
   {MemberOrCallExpression
    {MemberExpression
     {PrimaryExpression
      (
      {AdditiveExpression
       {UnaryExpression
        +
        {UnaryExpression
         !
         {UnaryExpression
          !
          {UnaryExpression
           {UpdateExpression
            {MemberOrCallExpression
             {MemberExpression
              {PrimaryExpression
               {ArrayLiteral
                []
       +
       {AdditiveExpression
        {UnaryExpression
         {UpdateExpression
          {MemberOrCallExpression
           {MemberExpression
            {MemberExpression
             {PrimaryExpression
              (
              {AdditiveExpression
               {UnaryExpression
                !
                {UnaryExpression
                 !
                 {UnaryExpression
                  {UpdateExpression
                   {MemberOrCallExpression
                    {MemberExpression
                     {PrimaryExpression
                      {ArrayLiteral
                       []
               +
               {AdditiveExpression
                {UnaryExpression
                 {UpdateExpression
                  {MemberOrCallExpression
                   {MemberExpression
                    {PrimaryExpression
                     {ArrayLiteral
                      []
              )
            [
            {AdditiveExpression
             {UnaryExpression
              !
              {UnaryExpression
               !
               {UnaryExpression
                {UpdateExpression
                 {MemberOrCallExpression
                  {MemberExpression
                   {PrimaryExpression
                    {ArrayLiteral
                     []
             +
             {AdditiveExpression
              {UnaryExpression
               !
               {UnaryExpression
                !
                {UnaryExpression
                 {UpdateExpression
                  {MemberOrCallExpression
                   {MemberExpression
                    {PrimaryExpression
                     {ArrayLiteral
                      []
              +
              {AdditiveExpression
               {UnaryExpression
                !
                {UnaryExpression
                 !
                 {UnaryExpression
                  {UpdateExpression
                   {MemberOrCallExpression
                    {MemberExpression
                     {PrimaryExpression
                      {ArrayLiteral
                       []
            ]
        +
        {AdditiveExpression
         {UnaryExpression
          {UpdateExpression
           {MemberOrCallExpression
            {MemberExpression
             {PrimaryExpression
              (
              {AdditiveExpression
               {UnaryExpression
                +
                {UnaryExpression
                 !
                 {UnaryExpression
                  !
                  {UnaryExpression
                   {UpdateExpression
                    {MemberOrCallExpression
                     {MemberExpression
                      {PrimaryExpression
                       {ArrayLiteral
                        []
               +
               {AdditiveExpression
                {UnaryExpression
                 {UpdateExpression
                  {MemberOrCallExpression
                   {MemberExpression
                    {PrimaryExpression
                     {ArrayLiteral
                      [
                      {AdditiveExpression
                       {UnaryExpression
                        +
                        {UnaryExpression
                         {UpdateExpression
                          {MemberOrCallExpression
                           {MemberExpression
                            {PrimaryExpression
                             {ArrayLiteral
                              []
                       +
                       {AdditiveExpression
                        {UnaryExpression
                         {UpdateExpression
                          {MemberOrCallExpression
                           {MemberExpression
                            {PrimaryExpression
                             {ArrayLiteral
                              [
                              {AdditiveExpression
                               {UnaryExpression
                                +
                                {UnaryExpression
                                 {UpdateExpression
                                  {MemberOrCallExpression
                                   {MemberExpression
                                    {PrimaryExpression
                                     {ArrayLiteral
                                      []
                               +
                               {AdditiveExpression
                                {UnaryExpression
                                 {UpdateExpression
                                  {MemberOrCallExpression
                                   {MemberExpression
                                    {PrimaryExpression
                                     {ArrayLiteral
                                      [
                                      {AdditiveExpression
                                       {UnaryExpression
                                        +
                                        {UnaryExpression
                                         {UpdateExpression
                                          {MemberOrCallExpression
                                           {MemberExpression
                                            {PrimaryExpression
                                             {ArrayLiteral
                                              []
                                      ]
                              ]
                      ]
              )
      )
